services:
  ponteradio-worker:
    build: .
    container_name: navibeta-ponteradio-worker
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - pocketbase

networks:
  pocketbase:
    external: true
    name: ix-pocketbase_default
