/**
 * NaviSuite Calendar Feed - Google Apps Script
 * Deploy come Web App: esegui come proprietario, accesso "Chiunque".
 * Dopo il deploy copia l'URL /exec in assets/calendar-config.json -> feedBase.
 */
const NAVI = Object.freeze({
  apiKey:'AIzaSyBfJZWHjr3AIANDBj2p8uQ0_hbcHdmnSiE',
  databaseUrl:'https://navisuite-f116f-default-rtdb.europe-west1.firebasedatabase.app',
  publicScheduleUrl:'https://navisuite-f116f-default-rtdb.europe-west1.firebasedatabase.app/public/schedule.json',
  tokenProperty:'NAVISUITE_CALENDAR_TOKENS_V1',authProperty:'NAVISUITE_FIREBASE_AUTH_V1',timezone:'Europe/Rome'
});
function doGet(e){const token=String(e?.parameter?.token||'').trim();if(!/^[a-f0-9]{64}$/i.test(token))return text_('Calendario NaviSuite: link non valido.');const record=readTokens_()[token];if(!record?.agentId)return text_('Calendario NaviSuite: link revocato o non valido.');try{return ContentService.createTextOutput(buildCalendar_(String(record.agentId))).setMimeType(ContentService.MimeType.ICAL)}catch(error){console.error(error);return text_('Calendario NaviSuite temporaneamente non disponibile.')}}
function doPost(e){const p=e?.parameter||{},action=String(p.action||'').trim().toLowerCase(),agentId=String(p.agentId||'').trim(),token=String(p.token||'').trim().toLowerCase(),proof=String(p.proof||'').trim().toLowerCase();try{if(!agentId||!/^[a-f0-9]{64}$/.test(proof))throw new Error('Credenziali non valide');if(!verifyUser_(agentId,proof))throw new Error('PIN non valido');const tokens=readTokens_();if(action==='register'){if(!/^[a-f0-9]{64}$/.test(token))throw new Error('Token non valido');tokens[token]={agentId,createdAt:new Date().toISOString()};writeTokens_(tokens);return json_({ok:true,action:'register'})}if(action==='revoke'){if(tokens[token]&&String(tokens[token].agentId)===agentId)delete tokens[token];writeTokens_(tokens);return json_({ok:true,action:'revoke'})}throw new Error('Azione non supportata')}catch(error){return json_({ok:false,error:String(error?.message||error)})}}
function text_(v){return ContentService.createTextOutput(String(v||'')).setMimeType(ContentService.MimeType.TEXT)}
function json_(v){return ContentService.createTextOutput(JSON.stringify(v||{})).setMimeType(ContentService.MimeType.JSON)}
function readTokens_(){try{return JSON.parse(PropertiesService.getScriptProperties().getProperty(NAVI.tokenProperty)||'{}')||{}}catch(_){return{}}}
function writeTokens_(v){PropertiesService.getScriptProperties().setProperty(NAVI.tokenProperty,JSON.stringify(v||{}))}
function safeKey_(v){return String(v||'').trim().replace(/[.#$\[\]\/]/g,'_')}
function verifyUser_(id,proof){const saved=firebaseGet_('private/adminUpdates/userAuth/'+encodeURIComponent(safeKey_(id)))||{};return String(saved.pinHash||'').toLowerCase()===String(proof||'').toLowerCase()}
function firebaseGet_(path){const auth=firebaseAuth_(),url=NAVI.databaseUrl+'/'+String(path||'').replace(/^\/+/, '')+'.json?auth='+encodeURIComponent(auth.idToken),response=UrlFetchApp.fetch(url,{muteHttpExceptions:true,headers:{Accept:'application/json'}});if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('Firebase HTTP '+response.getResponseCode());const text=response.getContentText();return text?JSON.parse(text):null}
function firebaseAuth_(){const props=PropertiesService.getScriptProperties();let auth=null;try{auth=JSON.parse(props.getProperty(NAVI.authProperty)||'null')}catch(_){}if(auth?.idToken&&Number(auth.expiresAt||0)>Date.now()+120000)return auth;if(auth?.refreshToken){try{const response=UrlFetchApp.fetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(NAVI.apiKey),{method:'post',muteHttpExceptions:true,contentType:'application/x-www-form-urlencoded',payload:{grant_type:'refresh_token',refresh_token:auth.refreshToken}}),data=JSON.parse(response.getContentText()||'{}');if(response.getResponseCode()>=200&&response.getResponseCode()<300&&data.id_token){auth={uid:data.user_id,idToken:data.id_token,refreshToken:data.refresh_token,expiresAt:Date.now()+Number(data.expires_in||3600)*1000};props.setProperty(NAVI.authProperty,JSON.stringify(auth));return auth}}catch(_){}}const response=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(NAVI.apiKey),{method:'post',muteHttpExceptions:true,contentType:'application/json',payload:JSON.stringify({returnSecureToken:true})}),data=JSON.parse(response.getContentText()||'{}');if(response.getResponseCode()<200||response.getResponseCode()>=300||!data.idToken)throw new Error('Autenticazione Firebase non riuscita');auth={uid:data.localId,idToken:data.idToken,refreshToken:data.refreshToken,expiresAt:Date.now()+Number(data.expiresIn||3600)*1000};props.setProperty(NAVI.authProperty,JSON.stringify(auth));return auth}
function publicSchedule_(){const response=UrlFetchApp.fetch(NAVI.publicScheduleUrl+'?t='+Date.now(),{muteHttpExceptions:true,headers:{Accept:'application/json'}});if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('Turni non disponibili');return JSON.parse(response.getContentText()||'{}')||{}}
function norm_(v){return String(v||'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,' ').trim()}
function stableUid_(v){const n=norm_(v).replace(/\s+/g,'_');return n?'AG_'+n:''}
function normalizedShift_(v){const raw=String(v??'').trim().toUpperCase().replace(/[‐‑–—]/g,'-');if(!raw||/^(?:RIP(?:\.|-*)?|RIPOSO|-{2,}|={2,})$/.test(raw))return'RIP';if(/^(?:CONG?\.?|CON;|CONC\.?|C\.)$/.test(raw))return'CON';if(/^(?:LAV\.?|TERRA)$/.test(raw))return'TERRA';if(/^F\.?P\.?-*$/.test(raw))return'F.P.';return raw.replace(/\.{2,}$/g,'.').replace(/-+$/g,'')}
function courseShift_(v){const raw=String(v||'').trim().toUpperCase().replace(/[‐‑–—]/g,'-').replace(/\s+/g,''),m=raw.match(/^C?(D[1-4]|BIS|T[12]|M1|R[1-4]|CAR\d*|P[1-3]|CAP\d*|SR1)C?$/);if(!m)return'';const direct=m[1],code=direct.replace(/\d+$/,'');return code==='CAR'||code==='CAP'?code:direct}
function isWorking_(v){const s=normalizedShift_(v);return Boolean(s)&&!/^(?:RIP|RIPOSO|CON|CONG|CONGEDO|FERIE|MAL|MALATTIA|F\.P\.|FP|===|--+)$/i.test(s)}
function values_(v){if(Array.isArray(v))return v.filter(Boolean);if(!v||typeof v!=='object')return[];return Object.keys(v).map(k=>v[k]).filter(Boolean)}
function flatten_(data){const result=[],seen={};Object.keys(data.residenze||{}).forEach(residence=>(data.residenze[residence]||[]).forEach(agent=>{const key=String(agent.agent_uid||agent.id||stableUid_(agent.agente));if(!key||seen[key])return;seen[key]=true;const copy=JSON.parse(JSON.stringify(agent||{}));copy.__residence=residence;result.push(copy)}));return result}
function applyImports_(data,imports){const active=values_(imports).filter(x=>x&&x.attiva!==false).sort((a,b)=>String(a.importedAt||'').localeCompare(String(b.importedAt||'')));if(!active.length)return;active.forEach(batch=>{const dates=Array.isArray(batch.dates)?batch.dates:[];values_(batch.rows).forEach(row=>{const agents=flatten_(data),uid=String(row.agent_uid||stableUid_(row.agente)),name=norm_(row.agente),target=agents.find(a=>String(a.agent_uid||stableUid_(a.agente))===uid)||(name?agents.find(a=>norm_(a.agente)===name):null)||agents.find(a=>String(a.id||'')===String(row.id_agente||''));if(!target)return;Object.keys(data.residenze||{}).some(res=>{const original=(data.residenze[res]||[]).find(a=>String(a.id||'')===String(target.id||'')||norm_(a.agente)===norm_(target.agente));if(!original)return false;original.turni=original.turni||{};dates.forEach((iso,i)=>original.turni[iso]=normalizedShift_((row.turni||[])[i]));return true})})})}
function applyProfiles_(data,profiles){data.residenze=data.residenze||{};values_(profiles).forEach(item=>{if(!item||!String(item.id||'').trim()||!String(item.residence||'').trim())return;const residence=String(item.residence).trim(),list=data.residenze[residence]=data.residenze[residence]||[];if(!list.some(a=>String(a.id||'')===String(item.id)))list.push({agente:String(item.name||item.id),id:String(item.id),qualifica:String(item.qualifica||''),role:String(item.role||''),turni:{},turni_settimanali:{}})})}
function mergeData_(){const data=publicSchedule_();let updates={};try{updates=firebaseGet_('private/adminUpdates')||{}}catch(_){updates={}}applyImports_(data,updates.scheduleImports);applyProfiles_(data,updates.agentProfiles||{});data.variazioni_ods=values_(updates.odsVariations).concat(values_(updates.manualVariations));const rows=values_(data.turni_navi).concat(values_(updates.turniNavi)),byKey={};rows.forEach(item=>{if(!item)return;byKey[String(item.data||'')+'|'+String(item.corsa||item.turno||'')+'|'+String(item.nave||'')]=item});data.turni_navi=values_(byKey);return data}
function variationMap_(data){const map={};values_(data.variazioni_ods).forEach(item=>{if(!item||item.attiva===false)return;const iso=String(item.data||item.date||'').slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(iso))return;const shift=item.turno_nuovo??item.turno??item.dopo;if(shift==null)return;if(item.id_agente||item.agentId)map['id:'+String(item.id_agente||item.agentId)+'|'+iso]=shift;if(item.agente||item.nome)map['name:'+norm_(item.agente||item.nome)+'|'+iso]=shift});return map}
function effective_(agent,iso,map){const id=String(agent.id||agent.agent_uid||''),changed=map['id:'+id+'|'+iso],named=map['name:'+norm_(agent.agente||agent.name)+'|'+iso];return normalizedShift_(changed!=null?changed:(named!=null?named:(agent.turni||{})[iso]))}
function ship_(data,iso,shift){const course=courseShift_(shift);if(!course)return null;return values_(data.turni_navi).find(item=>item&&item.attiva!==false&&String(item.data||'').slice(0,10)===iso&&courseShift_(item.corsa||item.turno)===course)||null}
function role_(a){const v=String(a.qualifica||a.grado||a.role||'');if(/capitano|comandante/i.test(v))return'Capitano';if(/capo\s*timoniere|capotimoniere/i.test(v))return'Capo timoniere';if(/motorista/i.test(v))return'Motorista';if(/timoniere/i.test(v))return'Timoniere';if(/aiuto\s*motorista|aiutomotorista/i.test(v))return'Aiuto motorista';if(/marinaio/i.test(v))return'Marinaio';if(/barista/i.test(v))return'Barista';return v||'Equipaggio'}
function crew_(data,iso,shift,map){const course=courseShift_(shift);if(!course)return[];return flatten_(data).filter(a=>courseShift_(effective_(a,iso,map))===course).map(a=>String(a.agente||a.name||'').trim()+' ('+role_(a)+')')}
function buildCalendar_(agentId){const data=mergeData_(),agents=flatten_(data),agent=agents.find(a=>String(a.id||'')===String(agentId));if(!agent)throw new Error('Agente non trovato');const map=variationMap_(data),dates={};values_(data.date).forEach(item=>{const iso=String(item.iso||'');if(/^\d{4}-\d{2}-\d{2}$/.test(iso))dates[iso]=true});Object.keys(agent.turni||{}).forEach(iso=>{if(/^\d{4}-\d{2}-\d{2}$/.test(iso))dates[iso]=true});const stamp=Utilities.formatDate(new Date(),'UTC',"yyyyMMdd'T'HHmmss'Z'"),name=String(agent.agente||agent.name||agentId).trim(),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//NaviSuite//Calendario personale//IT','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:'+esc_('NaviSuite - '+name),'X-WR-TIMEZONE:Europe/Rome','REFRESH-INTERVAL;VALUE=DURATION:PT1H','X-PUBLISHED-TTL:PT1H'];Object.keys(dates).sort().forEach(iso=>{const shift=effective_(agent,iso,map);if(!isWorking_(shift))return;const s=ship_(data,iso,shift),vessel=String(s?.nave||s?.nome_nave||'').trim(),description=['Servizio: '+shift];if(vessel)description.push('Nave: '+vessel);const berth=String(s?.ormeggio_serale||s?.ormeggio||s?.ormeggioSera||'').trim();if(berth)description.push('Ormeggio serale: '+berth);const refuel=String(s?.rifornimento_mattina||s?.rifornimento||s?.rifornimentoMattina||'').trim();if(refuel)description.push('Rifornimento: '+refuel);const crew=crew_(data,iso,shift,map);if(crew.length)description.push('','Equipaggio:');crew.forEach(person=>description.push('• '+person));description.push('','Generato da NaviSuite');lines.push('BEGIN:VEVENT','UID:'+String(agentId).replace(/[^A-Za-z0-9_-]/g,'_')+'-'+iso+'@navisuite','DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+iso.replace(/-/g,''),'DTEND;VALUE=DATE:'+next_(iso).replace(/-/g,''),'SUMMARY:'+esc_('NaviSuite · '+shift+(vessel?' · '+vessel:'')),'DESCRIPTION:'+esc_(description.join('\n')),'STATUS:CONFIRMED','TRANSP:TRANSPARENT','END:VEVENT')});lines.push('END:VCALENDAR');return lines.map(fold_).join('\r\n')+'\r\n'}
function next_(iso){const p=iso.split('-').map(Number),d=new Date(Date.UTC(p[0],p[1]-1,p[2]+1,12));return Utilities.formatDate(d,'UTC','yyyy-MM-dd')}
function esc_(v){return String(v??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function fold_(line){const chunks=[];let rest=String(line||'');while(rest.length>72){chunks.push(rest.slice(0,72));rest=rest.slice(72)}chunks.push(rest);return chunks.join('\r\n ')}
